setwd("C:\\Users\\qitcw\\Desktop\\pmdata")
pmemi <- readRDS("pm2.5 emmision.rds")
sub2 <- subset(pmemi, fips=="24510")
years <- as.factor(sub2$year)
png("plot3.png", height = 480, width = 480)
library(ggplot2)
G0 <- ggplot(sub2, aes(years, Emissions, fill = type)) + geom_bar(stat = "sum") + facet_grid(.~ type) + ylab("Total PM2.5 Emission (tons)")
print(G0)
dev.off()
